# action.yml
name: 'Update Kustomize Image Tag'
description: 'updates the image tag of kustomize kustomization file'
inputs:
  imageName:
    description: 'What image name to update tag on'
    required: true
  newImageTag:
    description: 'The new Image tag to update to'
    required: true
  environment:
    description: 'What environment folder to update'
    default: 'dev'
  defaultFolder:
    description: 'What is the default kustomize folder'
    default: './kustomize'
  defaultFileExtension:
    description: 'What is the default kustomize file extension'
    default: '.yaml'
runs:
  using: 'docker'
  image: 'Dockerfile'